name: ✨ Feature Request
description: Suggest an idea or enhancement for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the information below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve? What's missing or frustrating?
      placeholder: I'm frustrated when... / I need to... / It would be better if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this problem to be solved? What should the feature do?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've thought about
    validations:
      required: false

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What area of the project does this feature relate to?
      options:
        - Installation/Setup
        - Documentation
        - AI Rules/Behavior
        - Staleness Checking
        - Cross-Platform Support
        - Examples/Templates
        - Testing/Validation
        - Other (specify in description)
    validations:
      required: false

  - type: dropdown
    id: willingness
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to contribute this feature via a pull request?
      options:
        - "Yes, I'd like to implement this"
        - "I can help with testing"
        - "I can help with documentation"
        - "No, but I can provide feedback"
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / User Story
      description: |
        Help us understand how this feature would be used in practice.
        Example: "As a [type of user], I want [feature] so that [benefit]"
      placeholder: |
        As a developer working on a team...
        When I'm setting up a new project...
        I want to...
        So that...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context, mockups, or examples about the feature request here.
        - Links to similar features in other projects
        - Screenshots or mockups
        - Code examples
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Before Submitting
      description: Please confirm you've done the following
      options:
        - label: I have searched existing issues and discussions to ensure this feature hasn't been requested yet
          required: true
        - label: I have checked the [Roadmap](https://github.com/u00dxk2/cursor-kooi-env-docs#-roadmap) to see if this is already planned
          required: false
